version: '3.8'

services:
  postgres:
    container_name: rinha_db
    image: postgres:16.2
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: postgres -c max_connections=1000 -c max_wal_size=4096 -c checkpoint_timeout=600 -c synchronous_commit=off -c effective_cache_size=225MB -c shared_buffers=75MB -c fsync=off -c huge_pages=off -c work_mem=100MB -c maintenance_work_mem=256MB -c effective_io_concurrency=4
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '350MB'

  api1: &api
    build: .
    container_name: rinha_api_1
    hostname: api1
    depends_on:
      - postgres
    environment:
      - GOMAXPROCS=1
      - GOMEMLIMIT=75MiB
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '75MB'

  api2:
    <<: *api
    container_name: rinha_api_2
    hostname: api2

  nginx:
    image: nginx
    container_name: rinha_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50MB'